apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  annotations: {
    "kubernetes.io/ingress.class": "traefik"
  }
spec:
  rules:
  - host: {{ .Values.service.host }}
    http:
      paths:
      - path:
        backend:
          serviceName: {{ template "fullname" . }}
          servicePort: {{ .Values.service.externalPort }}
